language: php

# Add php version so composer doesn't complain
php:
  - 7.1

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html
  - APOLLO_URL=apollo:8888

before_script:
- tar -xvf example_data/yeast.tar.gz -C example_data/
- docker-compose up -d
- sleep 300

script:
  - sh setup/set_travis_apollo.sh
  - docker-compose exec app drush pm-enable -y tripal_apollo
  - docker-compose execp app bash -c "cd /modules/tripal_apollo && composer install && DRUPAL_ROOT=/var/www/html ./vendor/bin/phpunit"
