language: php

# Add php version so composer doesn't complain
php:
  - 7.1

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html

before_script:
- tar -xvf example_data/yeast.tar.gz -C example_data/
- docker-compose up -d
- sleep 300

script:
  - APOLLO_URL=http://127.0.0.1:8888 && export APOLLO_URL
  - sh setup/set_travis_apollo.sh
 # - docker commit start tripal_apollo_appolo_1
  - docker-compose exec app drush pm-enable -y tripal_apollo
  - docker-compose exec app bash -c "cd /modules/tripal_apollo && composer install && DRUPAL_ROOT=/var/www/html APOLLO_URL=http://tripal_apollo_apollo_1:8080 ./vendor/bin/phpunit"
